# Use root/root user/password credentials
version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ../../code/elastic:/var/lib/elastic
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  elasticsearch-data:
