# Use root/root user/password credentials
version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    container_name: php7.1
    volumes:
      - "${HOME}/workspace/www:/var/www"
      - "${HOME}/workspace/vhosts:/etc/apache2/sites-enabled"

