#!/bin/bash

source "lampPath.sh"

source "${BASE_PATH}/functions/textStyles.sh"
source "${BASE_PATH}/functions/noArguments.sh"
source "${BASE_PATH}/functions/oneArgument.sh"
source "${BASE_PATH}/functions/twoArguments.sh"
source "${BASE_PATH}/functions/moreThanTwoArguments.sh"


if [[ $# == 0 ]]; 
then
    noArguments
elif [[ $# == 1 ]]; 
then
    echo $LAMP_PATH
    oneArgument $1
elif [[ $# == 2 ]]; 
then
    twoArguments $1 $2
elif [[ $# > 2 ]]; 
then
    moreThanTwoArguments
fi
