# Use root/root user/password credentials
version: '3.7'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../../code/mysql:/var/lib/mysql

volumes:
  mysql-data:
