#!/bin/bash

echoHelp () {
  echo "Options: "
  echo "db		Stop and remove mysql5.6 container"
  echo "5.4		Stop and remove php5.4 container"
  echo "5.6		Stop and remove php5.6 container"
  echo "7.0		Stop and remove php7.0 container"
  echo "7.1		Stop and remove php7.1 container"
  echo "7.2		Stop and remove php7.2 container"
  echo "7.4		Stop and remove php7.4 container"
}

  if [[ "$1" = "--help" ]];
  then
    echoHelp
elif [[ "$1" == "db" ]];
then
	cd ~/docker/mysql5.6
	docker-compose down
else
	cd ~/docker/php$1
	docker-compose down
fi