# Use root/root user/password credentials
version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - "~/workspace/www:/var/www"
      - "~/workspace/vhosts:/etc/apache2/sites-enabled"
networks:
  lamp: {}
